rd /s/q obj
rem rd /s/q bin
rd /s/q tst\Simple\obj
rd /s/q tst\Simple\bin
rd /s/q tst\Guess\obj
rd /s/q tst\Guess\bin
rd /s/q tst\TransparentGuess\obj
rd /s/q tst\TransparentGuess\bin
rd /s/q tst\PropGuess\obj
rd /s/q tst\PropGuess\bin
rd /s/q tst\TestIndex\obj
rd /s/q tst\TestIndex\bin
rd /s/q tst\TestRegex\obj
rd /s/q tst\TestRegex\bin
rd /s/q tst\TestPerf\obj
rd /s/q tst\TestPerf\bin
rd /s/q tst\TestProp\obj
rd /s/q tst\TestProp\bin
rd /s/q tst\TestKDTree\obj
rd /s/q tst\TestKDTree\bin
rd /s/q tst\TestKDTree2\obj
rd /s/q tst\TestKDTree2\bin
rd /s/q tst\TestNullable\obj
rd /s/q tst\TestNullable\bin
rd /s/q tst\TestIndexCE\obj
rd /s/q tst\TestIndexCE\bin
rd /s/q tst\TestMap\obj
rd /s/q tst\TestMap\bin
rd /s/q tst\TestIndex2\obj
rd /s/q tst\TestIndex2\bin
rd /s/q tst\TestLink\obj
rd /s/q tst\TestLink\bin
rd /s/q tst\TestLinq\obj
rd /s/q tst\TestLinq\bin
rd /s/q tst\TestList\obj
rd /s/q tst\TestList\bin
rd /s/q tst\TestList2\obj
rd /s/q tst\TestList2\bin
rd /s/q tst\TestRndIndex\obj
rd /s/q tst\TestRndIndex\bin
rd /s/q tst\TestGC\obj
rd /s/q tst\TestGC\bin
rd /s/q tst\TestConcur\obj
rd /s/q tst\TestConcur\bin
rd /s/q tst\TestLockUpgrade\obj
rd /s/q tst\TestLockUpgrade\bin
rd /s/q tst\TestServer\obj
rd /s/q tst\TestServer\bin
rd /s/q tst\TestDbServer\obj
rd /s/q tst\TestDbServer\bin
rd /s/q tst\TestRtree\obj
rd /s/q tst\TestRtree\bin
rd /s/q tst\TestR2\obj
rd /s/q tst\TestR2\bin
rd /s/q tst\TestTtree\obj
rd /s/q tst\TestTtree\bin
rd /s/q tst\TestXML\obj
rd /s/q tst\TestXML\bin
rd /s/q tst\TestBackup\obj
rd /s/q tst\TestBackup\bin
rd /s/q tst\TestRaw\obj
rd /s/q tst\TestRaw\bin
rd /s/q tst\TestSSD\bin
rd /s/q tst\TestSSD\obj
rd /s/q tst\JsqlSSD\bin
rd /s/q tst\JsqlSSD\obj
rd /s/q tst\TestSOD\bin
rd /s/q tst\TestSOD\obj
rd /s/q tst\TestEnumerator\obj
rd /s/q tst\TestEnumerator\bin
rd /s/q tst\TestCompoundIndex\obj
rd /s/q tst\TestCompoundIndex\bin
rd /s/q tst\TestBlob\obj
rd /s/q tst\TestBlob\bin
rd /s/q tst\TestFullTextIndex\obj
rd /s/q tst\TestFullTextIndex\bin
rd /s/q tst\SearchEngine\obj
rd /s/q tst\SearchEngine\bin
rd /s/q tst\TestAlloc\obj
rd /s/q tst\TestAlloc\bin
rd /s/q tst\TestBit\obj
rd /s/q tst\TestBit\bin
rd /s/q tst\TestBitmap\obj
rd /s/q tst\TestBitmap\bin
rd /s/q tst\TestReplic\obj
rd /s/q tst\TestReplic\bin
rd /s/q tst\TestReplic2\obj
rd /s/q tst\TestReplic2\bin
rd /s/q tst\TestTimeSeries\obj
rd /s/q tst\TestTimeSeries\bin
rd /s/q tst\IpCountry\obj
rd /s/q tst\IpCountry\bin
rd /s/q tst\TestJSQL\bin
rd /s/q tst\TestJSQL\obj
rd /s/q tst\TestJsqlJoin\bin
rd /s/q tst\TestJsqlJoin\obj
rd /s/q tst\TestCodeGenerator\bin
rd /s/q tst\TestCodeGenerator\obj
rd /s/q tst\TestAutoIndices\bin
rd /s/q tst\TestAutoIndices\obj
rd /s/q Rdf\bin
rd /s/q Rdf\obj
rd /s/q Rdf\XmlServer\bin
rd /s/q Rdf\XmlServer\obj
del /q Rdf\samples\*.dbs
del /q tst\IpCountry\*.dbs
del /q tst\*.dbs
del /q tst\*.log
del /q tst\*.map
del /q tst\*.xml
del /q *.dbs
del /q *.map
del /q *.xml
del /q *.suo
del /q *.ncb
cd ..
del /q perst4net.zip
zip -r perst4net.zip Perst4.NET -x "Perst4.NET/doc/sources/*"
