nmake %* TARGET=NET_1.0
nmake %* clean
nmake %* TARGET=GENERICS
nmake %* clean
nmake %* TARGET=COMPACT_NET_1.0
nmake %* clean
nmake %* TARGET=COMPACT_NET_2.0
nmake %* clean
nmake %* TARGET=COMPACT_NET_3.5
nmake %* clean
nmake %* TARGET=SILVERLIGHT
nmake %* clean
nmake %* TARGET=SILVERLIGHT_GENERICS
nmake %* clean
nmake %* TARGET=NET_3.5
nmake %* clean
nmake %* TARGET=NET_4.0
nmake %* clean
nmake %* TARGET=NET_2.0
